language: node_js
node_js:
    - node
    - 'lts/*'
    - '12'
    - 12.14.0
env: null
global:
    - SERVER_PROTOCOL=http
    - SERVER_HOSTNAME=localhost
    - SERVER_PORT=8080
    - USER_DB_SERVER_PROTOCOL=mongodb
    - USER_DB_SERVER_HOSTNAME=localhost
    - USER_DB_SERVER_PORT=27017
    - USER_DB_SERVER_USERNAME=iotuserdatabase-user
    - USER_DB_SERVER_PASSWORD=iotuserdatabase-pwd
    - USER_DB_SERVER_DATABASE=iot-user-database
    - APP_NAME=iot-user-provisioner
    - APP_VERSION=1
    - APP_LOG_FILE=iot-user-provisioner
