version: '3.1'

services:

  mongo:
    image: mongo
    container_name: 'iot-user-mongodb'
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=iot-user-database
      - MONGO_INITDB_ROOT_USERNAME=iot-user-root
      - MONGO_INITDB_ROOT_PASSWORD=iot-user-passwd
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   depends_on: 
  #     - mongo
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: iot-user-root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: iot-user-passwd
