name: "Run tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Decrypt secrets
      run: npm run secrets:decrypt


    - name: Install dependencies
      run: npm i
    - name: Unit test
      run: npm run test:unit
    - name: Code coverage
      run: npm run test:coverage

