name: "Run tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Tests:
  #   runs-on: ubuntu-latest
  #   env:
  #     ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Set up Node 14
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: '14'

  #   - name: Decrypt secrets
  #     run: npm run secrets:decrypt

  #   - name: Install dependencies
  #     run: npm i

  #   - name: Unit test
  #     run: npm run test:unit

  #   - name: Code coverage
  #     run: npm run test:unit:coverage

  #   - name: End to End Tests
  #     run: npm run test:e2e-container

  Image-Build:
    # needs: Tests
    runs-on: ubuntu-latest
    env:
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Decrypt secrets
      run: npm run secrets:decrypt

    - name: Install dependencies
      run: npm i

    - name: 'Build Stage'
      run: npm run build:prod

    # - name: 'Image build'
    #   run: npm run build:container

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Push to GitHub Packages'
      run: |
        npm run build:container
        docker push ghcr.io/iot-stuff/iot-user-provisioner
